"""add unqiue patient id, doctor id

Revision ID: 1997abce4139
Revises: f6f0bc853e47
Create Date: 2025-10-12 14:59:27.736254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1997abce4139'
down_revision: Union[str, Sequence[str], None] = 'f6f0bc853e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('eq_patient_doctor', 'association_table', ['patient_id', 'doctor_id'])
    op.drop_constraint(op.f('patient_first_name_last_name_middle_name_birthday_key'), 'patient', type_='unique')
    op.create_unique_constraint(None, 'patient', ['first_name', 'last_name', 'middle_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient', type_='unique')
    op.create_unique_constraint(op.f('patient_first_name_last_name_middle_name_birthday_key'), 'patient', ['first_name', 'last_name', 'middle_name', 'birthday'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('eq_patient_doctor', 'association_table', type_='unique')
    # ### end Alembic commands ###
