"""+ bmr

Revision ID: 1dc4016a82a1
Revises: 6216145cde13
Create Date: 2025-11-01 14:41:49.026224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc4016a82a1'
down_revision: Union[str, Sequence[str], None] = '6216145cde13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mbr',
    sa.Column('formula', sa.Enum('mif_sanj', 'har_ben', name='bmr_enum'), nullable=False),
    sa.Column('bmr_value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('patient', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mbr')
    # ### end Alembic commands ###
