"""rename table

Revision ID: 245e54ba1e18
Revises: 1dc4016a82a1
Create Date: 2025-11-01 14:45:17.118003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '245e54ba1e18'
down_revision: Union[str, Sequence[str], None] = '1dc4016a82a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bmr',
    sa.Column('formula', sa.Enum('mif_sanj', 'har_ben', name='bmr_enum'), nullable=False),
    sa.Column('bmr_value', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('patient', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient'], ['patient.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('mbr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mbr',
    sa.Column('bmr_value', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('patient', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient'], ['patient.id'], name=op.f('mbr_patient_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('mbr_pkey'))
    )
    op.drop_table('bmr')
    # ### end Alembic commands ###
