"""add cascade

Revision ID: 37bf75ab6471
Revises: 2f601b774929
Create Date: 2025-10-25 15:17:56.057262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bf75ab6471'
down_revision: Union[str, Sequence[str], None] = '2f601b774929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('patient2doctor_doctor_id_fkey'), 'patient2doctor', type_='foreignkey')
    op.drop_constraint(op.f('patient2doctor_patient_id_fkey'), 'patient2doctor', type_='foreignkey')
    op.create_foreign_key(None, 'patient2doctor', 'doctor', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'patient2doctor', 'patient', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient2doctor', type_='foreignkey')
    op.drop_constraint(None, 'patient2doctor', type_='foreignkey')
    op.create_foreign_key(op.f('patient2doctor_patient_id_fkey'), 'patient2doctor', 'patient', ['patient_id'], ['id'])
    op.create_foreign_key(op.f('patient2doctor_doctor_id_fkey'), 'patient2doctor', 'doctor', ['doctor_id'], ['id'])
    # ### end Alembic commands ###
