"""add default to created_at, updated_at

Revision ID: 6216145cde13
Revises: 643043f2547c
Create Date: 2025-10-28 16:17:21.280612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6216145cde13'
down_revision: Union[str, Sequence[str], None] = '643043f2547c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('doctor', 'middle_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('patient', 'middle_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'middle_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('doctor', 'middle_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
