"""delete reference

Revision ID: e267dd5dc351
Revises: 245e54ba1e18
Create Date: 2025-11-01 15:04:43.341955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e267dd5dc351'
down_revision: Union[str, Sequence[str], None] = '245e54ba1e18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bmr', sa.Column('patient_id', sa.BigInteger(), nullable=False))
    op.drop_constraint(op.f('bmr_patient_fkey'), 'bmr', type_='foreignkey')
    op.create_foreign_key(None, 'bmr', 'patient', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bmr', 'patient')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bmr', sa.Column('patient', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'bmr', type_='foreignkey')
    op.create_foreign_key(op.f('bmr_patient_fkey'), 'bmr', 'patient', ['patient'], ['id'], ondelete='CASCADE')
    op.drop_column('bmr', 'patient_id')
    # ### end Alembic commands ###
